-- 코드를 입력하세요 내가 푼 거
SELECT A.ANIMAL_ID,A.ANIMAL_TYPE,A.NAME
FROM ANIMAL_INS A JOIN ANIMAL_OUTS B USING(ANIMAL_ID)
WHERE A.SEX_UPON_INTAKE != B.SEX_UPON_OUTCOME

-- 코드를 입력하세요 다른사람이 푼 거 정규식 사용
# SELECT A.ANIMAL_ID
#     , A.ANIMAL_TYPE
#     , A.NAME
# FROM ANIMAL_INS A
# JOIN ANIMAL_OUTS B USING (ANIMAL_ID)
# WHERE A.SEX_UPON_INTAKE NOT REGEXP 'Spayed|Neutered'
# AND B.SEX_UPON_OUTCOME REGEXP 'Spayed|Neutered'
# ORDER BY A.ANIMAL_ID
# ;