-- 코드를 입력하세요

WITH ReviewCounts AS (
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
), MaxCount AS (
    SELECT MEMBER_ID
    FROM ReviewCounts
    WHERE REVIEW_COUNT = (
        SELECT MAX(REVIEW_COUNT)
        FROM ReviewCounts 
        )
)
SELECT MEMBER_NAME,REVIEW_TEXT,DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M, REST_REVIEW R,MaxCount C
WHERE M.MEMBER_ID = R.MEMBER_ID AND M.MEMBER_ID = C.MEMBER_ID
ORDER BY REVIEW_DATE,REVIEW_TEXT