-- 코드를 작성해주세요
SELECT ID,FISH_NAME,I.LENGTH
FROM FISH_NAME_INFO N JOIN FISH_INFO I
ON N.FISH_TYPE = I.FISH_TYPE
WHERE (I.FISH_TYPE,I.LENGTH) IN 
(
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)