-- 코드를 입력하세요TITLE, 
SELECT A.TITLE, A.BOARD_ID,B.REPLY_ID,B.WRITER_ID,B.CONTENTS,
DATE_FORMAT(B.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B 
where A.BOARD_ID = B.BOARD_ID
and A.CREATED_DATE BETWEEN '2022-10-1' and '2022-10-31'
order by B.CREATED_DATE ASC , A.TITLE